clarity_ext/clarity.py, clarity_ext/context.py, clarity_ext/dilution.py, clarity_ext/domain/analyte.py, clarity_ext/domain/container.py, clarity_ext/repository/step_repository.py, clarity_ext/service/artifact_service.py, test/unit/clarity_ext/dilution/test_dilutions.py, test/unit/clarity_ext/dilution/test_update_fields.py, test/unit/clarity_ext/helpers.py
Implementations:
* Begin implementation for updating fields. 
* Add volume field in analyte
* Calculation of fields to be updated are placed in clarity-snpseq
* Add validations for source conc and volume
I have added tickets related to this in Jira: 
LIMS-643 Integration tests when updating entities
LIMS-651 Create generic implementation for updating db
LIMS-583 Show and handle errors and warnings
=> Update dilute fields

clarity_ext/domain/analyte.py, clarity_ext/domain/result_file.py, clarity_ext/repository/step_repository.py, clarity_ext/service/artifact_service.py, test/integration/domain/test_result_file.py, test/integration/test_context.py
=> Ensure ResultFile UDFs are updated on commit

clarity_ext/domain/analyte.py, clarity_ext/domain/artifact.py, clarity_ext/domain/result_file.py, clarity_ext/repository/step_repository.py
Function updated_rest_resource is now implemented for ResultFile as well as Analyte. This function is splitted up,
Artifact: Fetch values from mapped udf fields
Analyte, ResultFile: Fetch field values that's specific for each class.
=> Fix function updated_rest_resource

README.md, clarity_ext/context.py, clarity_ext/domain/aliquot.py, clarity_ext/domain/analyte.py, clarity_ext/domain/artifact.py, clarity_ext/domain/container.py, clarity_ext/driverfile.py, clarity_ext/extensions.py, clarity_ext/repository/step_repository.py, clarity_ext/service/artifact_service.py, test/integration/__init__.py, test/integration/clarity_steps.yml, test/integration/domain/test_result_file.py, test/integration/integration_config.py, test/integration/service/test_artifact_service.py, test/unit/clarity_ext/helpers.py, test/unit/clarity_ext/test_context.py
This pull request provides support for generating samplesheets. It also contains various related fixes and refactorings.
=> Support generation of samplesheet

test/unit/clarity_ext/dilution/test_dilutions.py, test/unit/clarity_ext/dilution/test_update_fields.py
Referers to https://github.com/Molmed/clarity-snpseq/pull/39
Which is a bug fix regarding udf reference mixmatch
=> Add test for dilution with concentration unit nM

clarity_ext/context.py, clarity_ext/dilution.py, test/unit/clarity_ext/dilution/test_dilutions.py
Refers to https://github.com/Molmed/clarity-snpseq/pull/40
=> Add option for including blanks in DilutionScheme

clarity_ext/context.py, clarity_ext/domain/container.py, clarity_ext/domain/result_file.py, clarity_ext/service/artifact_service.py, clarity_ext/service/file_service.py
- CSV handling
- Other framework fixes (see individual commits)
=> Various changes to support CSV files

test/unit/clarity_ext/dilution/test_dilutions.py
Refers to changes in https://github.com/Molmed/clarity-snpseq/pull/50.
Adding som unit tests.
=> Misc dilution bugfixes

clarity_ext/cli.py, clarity_ext/context.py, clarity_ext/driverfile.py, clarity_ext/extensions.py, clarity_ext/utils.py
- Move the logic to several individual methods
- Some cleanup
=> Refactor ExtensionService.execute

clarity_ext/dilution.py, clarity_ext/service/artifact_service.py, test/unit/clarity_ext/dilution/test_dilutions.py, test/unit/clarity_ext/dilution/test_pooling.py, test/unit/clarity_ext/dilution/test_update_fields.py, test/unit/clarity_ext/helpers.py
https://github.com/Molmed/clarity-ext/pull/69 with merge conflict fix.
=> Git edvard lims 809 fix update fields

clarity_ext/domain/analyte.py, clarity_ext/domain/process.py, clarity_ext/extensions.py, clarity_ext/utils.py
- UDFs not being handled correctly after refactoring
- When loading analytes, there may be no process output definitions in
the process type, but the assumption was that they would be always at
least 1
=> Fix two issues with generating samplesheet

clarity_ext/extensions.py, clarity_ext/service/file_service.py
- Also fix issue with line endings when using templates.
The templates should control the line endings.
- Minor refactoring
=> Fix an issue with newline when uploading

clarity_ext/service/dilution/extension.py, clarity_ext/service/dilution/service.py, clarity_ext/service/file_service.py
- Plus some formatting and minor refactorings
=> Support newline in CSVs

clarity_ext/context.py, clarity_ext/domain/__init__.py, clarity_ext/domain/analyte.py, clarity_ext/domain/container.py, clarity_ext/domain/process.py, clarity_ext/mappers/clarity_mapper.py, clarity_ext/repository/container_repository.py, clarity_ext/repository/step_repository.py, clarity_ext/service/dilution/service.py, clarity_ext/service/dilution/strategies.py, clarity_ext/utility/testing.py, test/unit/clarity_ext/domain/test_artifact.py, test/unit/clarity_ext/domain/test_udf_mapping_info.py
A few other related refactorings. I recommend looking into each commit for commits and an easier read.
=> Use Wells in SingleTransfer objects

clarity_ext/domain/container.py, clarity_ext/service/dilution/service.py
* Containers don't need the container type integers
* CSV files are now hanging on the TransferBatch objects
=> Fixes for XML generation

clarity_ext/service/dilution/handlers.py
- Add an error for max well volume
- Add an error for evaporation
- Remove warnings for splitting a batch or a row
=> Fix warnings and errors

clarity_ext/service/dilution/handlers.py, clarity_ext/service/dilution/service.py, clarity_ext/service/validation_service.py
Prepare clarity-ext to support for factor dilutions. Add handler for factor dilution and add field dilute_factor to single transfer.
=> Adding step for factor dilutions

clarity_ext/domain/artifact.py, clarity_ext/service/dilution/service.py
- Custom commands for the robots in the Transfer objects
- Slot positioning moved to handlers (in the site-specific repo)
- Minor changes
=> 1310 - Fixes for evaporation

clarity_ext/service/artifact_service.py
- Fetching parent input artifacts based on submitted sample did not work
when the parent is a pool.
=> 1332 - Fix getting parent input artifacts for pools

setup.py
Various fixes related to evaporation
=> 1121 - Deploy text files with pip install

clarity_ext/extensions.py, clarity_ext/service/dilution/service.py
- Warnings from transfers were not being logged
- Error/warning summary was not being shown
=> Fix warnings

clarity_ext/domain/artifact.py, clarity_ext/domain/container.py, clarity_ext/service/dilution/service.py, clarity_ext/utility/testing.py
- Add a test helper for mocking steps, in particular for pooled dilution.
- Related minor fixes
=> 1385 - StepScenarios

clarity_ext/service/dilution/service.py
=> Lims 1425 separated evaporation file

clarity_ext/service/dilution/service.py
Refers to the PR in snpseq with the same name (#2 ?)
=> Bugfix for single control sample in default bach

clarity_ext/service/dilution/service.py
In order to make the sort working properly.
=> Initiate is_temporary field for temp-plates

clarity_ext/utility/testing.py
=> Fix unit tests

clarity_ext/extensions.py
Adds a few methods that update UDF information in different ways.
UDFs with the same names are copied between artifacts (analyte, sample or pool).
=> Add methods for updating udf information

clarity_ext/service/file_service.py
Files were not being uploaded correctly when using the local_shared_file
in the file service. Add the queue mechanism to its own function.
=> Bug fixes for the file service

clarity_ext/extensions.py
Move this method one level down in the class hierarchy.
=> Move the file_prefix method

clarity_ext/domain/container.py, clarity_ext/service/dilution/service.py, clarity_ext/service/file_service.py
- Better support for seeing the original "virtual" transfer that should be executed.
- Includes related minor fixes (see individual commits)
=> Support pooling to 96 well plate

clarity_ext/service/dilution/service.py
=> Add fixed buffer volume

clarity_ext/service/file_service.py
Otherwise the script will fail in that case
=> Skip updating the step log if any sample is under review

clarity_ext/domain/container.py, clarity_ext/service/clarity_service.py
Adds support for changing container level UDFs on the domain objects.
=> Add support for container UDFs

clarity_ext/service/dilution/service.py
Purpose:
There is one dilution script (clustering.driverfile) that needs to sort with respect to sample end positions, as opposed to sample source positions previously used. 
Make it configurable to sort dilution driver files with respect to either source positions or target positions.
=> Add sort strategy to dilution setting

clarity_ext/context.py, clarity_ext/domain/analyte.py, clarity_ext/domain/reagent.py, clarity_ext/mappers/clarity_mapper.py, clarity_ext/repository/reagent_type_repository.py
Purpose:
Add reagent-type to the domain model, so that the attributes are written out explicitly. Also, initialize files for Errors and Warnings in the context class. 
reagent-type needs a repository, that is added.
=> 1540, Add reagent type to the domain model

clarity_ext/extensions.py, clarity_ext/service/dilution/index_generation.py
Purpose:
Move some code from clarity-snpseq-scripts (index file generation) to the framework. This code was previously only used in one script, but is now shared by two scripts.
=> 1959 convert index pos for hamilton

clarity_ext/service/dilution/service.py
Purpose:
In some cases, there is a need to choose between different strategies to solve a specific task. This new handler provides this feature. 
This PR is a preparation to handle two different strategies when pipetting volumes are too small at dilutions.
=> lims-2076, Add handler to choose between different strategies

clarity_ext/service/dilution/service.py, clarity_ext/service/step_logger_service.py
Purpose:
Prevent duplicate log messages to the step log.
=> lims-2088, Write unique log messages

clarity_ext/cli.py
=> Use yaml.safe_load

setup.py
These are used in particular to parse excel files, but also just for
anything pandas.
=> Add pandas and xlrd

clarity_ext/context.py, clarity_ext/domain/container.py, clarity_ext/domain/process.py, clarity_ext/domain/udf.py, clarity_ext/mappers/clarity_mapper.py, clarity_ext/service/artifact_service.py, clarity_ext/service/clarity_service.py, clarity_ext/service/file_service.py, setup.py, test/unit/clarity_ext/domain/test_udf_mapping_info.py
This PR includes all the changes that were made in the Covid project. These should be safe for SNP&SEQ, but I recommend that we do a full validation of our workflows when we start using this in that project.
=> Changes made during the covid project
