Molmed/clarity-ext

- clarity_ext/extensions.py
- The config file should not be required when running. It's
mainly necessary for testing and validation
- Also, fixed error in type check
> Add default configuration

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/container.py
- clarity_ext/domain/validation.py
- clarity_ext/driverfile.py
- clarity_ext/extensions.py
- clarity_ext/integration.py
- clarity_ext/pdf.py
- clarity_ext/result_file.py
- clarity_ext/unit_conversion.py
- clarity_ext/utility/hamilton_driver_file_reader.py
- All classes in clarity_ext should be new-style (inherit from object).
This is the default in py3.
> Use new-style classes

- clarity_ext/__init__.py
- clarity_ext/clarity.py
- clarity_ext/context.py
- clarity_ext/extensions.py
- The ClarityService class really encapsulates a session. Name it
accordingly
> Rename ClarityService to ClaritySession and move it

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/container.py
- test/integration/domain/test_artifact.py
- Fetch the `Analyte` domain objects through a repository only.
Don't access it directly through the REST API. This makes it possible
to mock this repository only when unit testing classes that use it.
- Stop sending in a `Plate` object
- Remove the MatchedAnalytes class, replace it with sorting logic in the
repository
- Update the dilutes module in relation to this
- Use the Container rather than the Plate object.
- Provide a resource when creating the domain `Container` object.
> Add a repository for analytes in the current step

- .gitignore
- clarity_ext/utils.py
- pre-commit.sh
- setup.py
- test/unit/clarity_ext/test_utils.py
- validate-integration.sh
- validate-unit.sh
- validate.sh
- Running the validate scripts now creates coverage files in ./cover
- Added a test for the lazyprop decorator
- Fixed some comments
- Add a script for cleaning up the syntax of all files changed in a
branch.
> Run test coverage when running the tests

- clarity_ext/domain/common.py
- clarity_ext/domain/container.py
- clarity_ext/repository/step_repository.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/helpers.py
Fix so that all integration tests work:
* Adapt _repr_ of well to handle if the container is not set. 
* Do not cast exception for ResultFile in update_objects in step_repository. Replace with TODO
Prevent an infinite loop when comparing equality for objects containing mutual references, e.g. Analyte --> well and Well --> artifact.
> Lims 655 bugfix

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/common.py
- clarity_ext/domain/container.py
- clarity_ext/driverfile.py
- clarity_ext/extensions.py
- clarity_ext/repository/step_repository.py
- clarity_ext/service/artifact_service.py
- clarity_ext/utils.py
- test/unit/clarity_ext/dilution/test_update_fields.py
Make possible to generate response for scripts that are updating fields in LIMS. 
Response generation:
* Use a cache with the original states of artifacts. Compare updated artifacts with this cache to extract a list of updated fields and their values.
* Export the response to a file named response.txt, in the same manner as in driver file generation (same code is used)
* It's possible to freeze the response to be used in integration tests, (same way as for driver files)
> Response from scripts at integrations tests

- clarity_ext/context.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/common.py
- clarity_ext/domain/result_file.py
- clarity_ext/driverfile.py
- clarity_ext/repository/step_repository.py
- clarity_ext/utils.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/helpers.py
Update to db reflects the state of the domain object. It's also possible to update udf that is not represented as an instance variable in the corresponding domain object. The function set_udf updates instance variable if it exists, otherwise, updates the api resource. When committing, all changes in instance variables are transferred to the api resources.
> Lims 683 set udf2

- clarity_ext/driverfile.py
- clarity_ext/extensions.py
- test/integration/integration_test_service.py
- test/unit/clarity_ext/helpers.py
- test/unit/clarity_ext/service/test_file_service.py
- test/unit/clarity_ext/utility/test_integration_test_service.py
Fix #1:
Fix shared file names for integration tests. Function shared_file in extension is to be used in production and be able to generate a file name based on current date and user initials, whereas integration tests use a shared file name already created and should therefore be hardcoded. 
Fix #2:
Possibility for preparation of integration tests. Source volume in dilutions are updated in a relative basis (current volume - dilute volume) and are therefor changing for each integration test run. Here is a class for running preparation code before the integration test is run. In this case, the volumes are updated to predefined values.
> Integration test fixes

- clarity_ext/domain/artifact.py
- clarity_ext/domain/result_file.py
- test/unit/clarity_ext/domain/test_artifact.py
There was a bug, originating from line 38 in artifact. A variable is called (self.units) that is never explicitly initialized in artifact. The derived class ResultFile had it defined but Analyte did not. So if Analyte was to be called with set_udf and a from_unit, the program would crash. 
I removed units from the input argument list, and instantiate it locally in artifact.
> Lims 703 unit conversion bugfix

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/user.py
- clarity_ext/driverfile.py
- clarity_ext/repository/step_repository.py
- test/integration/integration_test_service.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/dilution/test_update_fields.py
- test/unit/clarity_ext/helpers.py
- test/unit/clarity_ext/test_context.py
A dilution class is created, source only dilution scheme,  adapted for a dilution with no output analytes (qPCR). In this step there are only sample measurements as outputs (result_file). These changes have been made:
* Add class for user
* Refactor the Dilute class. Make it deal with units for input and output analytes separately.
* Refactor RobotDeckPositioner. Make it use two instances of the new class EndpointPositioner, which handles all plates for either source or destination.
> Lims 708 source only dilution scheme

- clarity_ext/dilution.py
- test/unit/clarity_ext/dilution/test_dilutions.py
In driver file generation, split up rows containing more than 50 ul of pipetting volume, either sample volume or buffer volume. 
In addition, scale up sample volumes less than 2 ul (min pipetting volume). This means that the entered target volume from user is also scaled up. 
Small refactoring: Sorting of the transfers are broken out from do_posiitoning, and called explicitly in __init__. Sorting also shows splitted up transfers in an intuitive order, higher volumes first.
> Lims 686 multiple rows for high volume transfers

- clarity_ext/extensions.py
I misunderstood the shared file name generation previously. It's constant between different protocol steps. The entry 'shared_file' is removed from the input argument list.
> Clean up unnessesary functionality for shared file handling

- clarity_ext/cli.py
- clarity_ext/context.py
- clarity_ext/driverfile.py
- clarity_ext/extensions.py
- clarity_ext/service/__init__.py
- clarity_ext/service/artifact_service.py
- clarity_ext/service/file_service.py
- clarity_ext/service/step_logger_service.py
- clarity_ext/unit_conversion.py
- test/integration/domain/test_result_file.py
- test/integration/test_context.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/test_context.py
- Ensures that all calls to the core logging framework end up
in /opt/clarity-ext/logs on a production server.
- Allows extension writers to write to log files on the step easily
> Add support for logging

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/aliquot.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/container.py
- clarity_ext/domain/result_file.py
- clarity_ext/domain/shared_result_file.py
- clarity_ext/repository/step_repository.py
- clarity_ext/service/artifact_service.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/dilution/test_update_fields.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/helpers.py
Prepare clarity ext dilutions for a step configured with input analytes and output result files. (The UI name for result file is sample measurement, which is a more appropriate name for it. ) The input analyte and output result file are forming a pair and should be treated in the same way as an analyte pair. I have created an common base class for them, Aliquot, which is now used in DilutionScheme class. 
Also, make some fixes regarding Well instantiation. Add some tests for create_from_rest_resource (result_file and analyte), and updated_rest_resource
> Lims 717 updated qpcr

- clarity_ext/dilution.py
- clarity_ext/domain/analyte.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/dilution/test_update_fields.py
- test/unit/clarity_ext/helpers.py
Add boolean is_control to analyte, in order to filter out control samples.
Update map creation for mapping between AliquotTransfers and Aliquot pairs.
> Filter out blank controls in dilution scheme

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/aliquot.py
- clarity_ext/domain/analyte.py
- clarity_ext/extensions.py
- clarity_ext/repository/step_repository.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/dilution/test_update_fields.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/helpers.py
Adjust clarity-ext so that it can make dilutions with concentration units ng/ul or nM. 
Import new udfs to analyte, refering to conc unit nM. Since calculations in DilutionScheme is independent of concentration unit, have a working variable for concentration, that can be initiated to either conc (ng/ul) or conc (nM). 
DilutionScheme now requires input argument concentration reference.
> Lims 731 cluster dilution

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/domain/aliquot.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/shared_result_file.py
- clarity_ext/extensions.py
- clarity_ext/repository/step_repository.py
- clarity_ext/service/step_logger_service.py
- clarity_ext/service/validation_service.py
- test/integration/integration_test_service.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/helpers.py
- test/unit/clarity_ext/service/test_validation_service.py
- test/unit/clarity_ext/test_step_repository.py
- test/unit/clarity_ext/utility/test_integration_test_service.py
Break out validation code from DriverFileExtension to the new class
ValidationService. Move validation code in DilutionScheme to snpseq
scripts.
Errors and warnings generated from the validation are exported to a file with entry name Errors_and_warning. The script with the validation code are typically triggered from a button, to give the user the opportunity to change parameters until she is satisfied, clicking the button several times if needed. 
There is a check if the user tries to go to the next step with unresolved errors. For this, there is a udf 'Has errors2' associated with the artifact for the Shared result file 'Errors_and_warnings', which is updated when needed each time the button-script is run.
> Lims 725 warning popup

- clarity_ext/context.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/udf.py
- test/unit/clarity_ext/test_context.py
At dilution steps (dna dilution + lib dilution), there is now a udf 'Print labels', that control if printing out labels or not, with default value 'no'. This udf should be shown during the validation period only.
In this pull request, make possible to get and set udfs for ExtensionContext. Previously, udfs could only be handled for Artifacts. 
Create the new base class Udf, and let both ExtensionContext and Artifact inherit from it. The code for udf handling is taken from the Artifact class.
> Add logic for supress printing out labels

- clarity_ext/context.py
- clarity_ext/dilution.py
- clarity_ext/dilution_strategies.py
- clarity_ext/domain/common.py
- clarity_ext/driverfile.py
- clarity_ext/extensions.py
- clarity_ext/repository/step_repository.py
- clarity_ext/service/artifact_service.py
- test/unit/clarity_ext/dilution/test_dilutions.py
- test/unit/clarity_ext/dilution/test_pooling.py
- test/unit/clarity_ext/dilution/test_update_fields.py
- test/unit/clarity_ext/helpers.py
Support driver file generation and updating udfs at pool creation steps. 
Implementation of function calculate_transfer_volumes is delegated out
to classes that is dedicated to the type of dilution:
* FixedVolumeCalc
* OneToOneConcentrationCalc
* PoolConcentrationCalc
The code in class PoolConcentrationCalc is new in this pull request. Here, source samples (representated by one end of a transfer
object) are first grouped so that there are a single destination pool within each group.
More information on how the calculation goes is written in the code comments.
> Make pooled dilutions

- clarity_ext/domain/aliquot.py
- clarity_ext/domain/udf.py
- This new mixin will replace the current one, simplifying how UDFs are
handled.
- For now, this is only being applied to `Sample` which was missing UDFs
altogether.
> Add DomainObjectWithUdfsMixin to Sample

- clarity_ext/cli.py
- clarity_ext/context.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/result_file.py
- clarity_ext/domain/shared_result_file.py
- clarity_ext/domain/udf.py
- clarity_ext/extensions.py
- clarity_ext/integration.py
- clarity_ext/service/artifact_service.py
- clarity_ext/service/file_service.py
- clarity_ext/service/step_logger_service.py
- clarity_ext/utils.py
- test/integration/integration_test_service.py
- Log files should be frozen along with generated data
- Support test_mode exeuction of extensions. These ensure that
generated data does remain constant between test runs.
- Support disabling commits while running extension integration tests
- Change the representation of a few domain objects, for log output
- Log UDF assignments so they can be compared between runs
- Add a handler for logging while testing. This handler only logs the
log entries that were logged during execution of the extension
and they land up in the run-test directory so they will eventually
be frozen.
- Add a new execution method for extensions, test-fresh, which ignores
the frozen cache
- Minor non-interface breaking related fixes
> Support freezing logs

- clarity_ext/context.py
- clarity_ext/domain/aliquot.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/result_file.py
- clarity_ext/mappers/clarity_mapper.py
- clarity_ext/repository/step_repository.py
- clarity_ext/service/artifact_service.py
- clarity_ext/service/clarity_service.py
- test/integration/clarity_steps.yml
- test/integration/domain/test_artifact.py
- test/integration/domain/test_result_file.py
- test/integration/service/test_artifact_service.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/helpers.py
- test/unit/clarity_ext/service/test_artifact_service.py
- validate-unit.sh
- validate.sh
- Create ClarityMapper, a mapper object between api objects and domain
objects. This will handle all the mapping in the future (ticket
created)
- Move factory methods from some domain objects to ClarityMapper
- Support updating sample UDFs
- Fix tests
- Fix validation scripts
> Start porting to ClarityMapper

- clarity_ext/domain/container.py
- clarity_ext/service/dilution/service.py
- Containers that have been positioned in a TransferBatch are now
wrapped in a ContainerSlot which knows about the index and the name
on the robot.
- Removed references to source_ref, target_ref etc.
> Introduce ContainerSlot

- clarity_ext/domain/udf.py
- Artifacts can be renamed. The code is a quick fix patch, but the
entire approach to updating should be overhauled in the next milestone.
> Support renaming artifacts

- clarity_ext/service/dilution/service.py
- clarity_ext/utility/testing.py
- Containers containing only the control where having an effect on the
index of other containers. So if there were 2 containers, they would
get the reference DNA1, DNA2, but one of those only has the control,
both should get the reference DNA1
- Minor fixes in related code
> Fix index of control containers

- clarity_ext/service/dilution/service.py
- We need a temporary check for is_pooled when fetching update infos
for a target analyte. The code segment being guarded by this setting
should only be executed in extensions that opt-in for it, i.e. this
should not be the default case for all pools.
- The name of the setting is not particularly good, but the plan is that
it's a temporary fix anyway.
> Add a temporary is_pooled setting

- clarity_ext/domain/container.py
- clarity_ext/service/dilution/service.py
- A recent fix should have made all source containers with a single control get
the index 0. However, the fix made all source containers that had any
control get the index 0. This patch fixes that.
- Minor bugfix for container to_string method (only used when debugging)
- Added the occupied method to the container for a simplified API
> Bugfix for container order

- clarity_ext/service/dilution/service.py
Negative controls that are added in current step are taken from the trough and should not be included in this list.
> Exclude controls from the source container list in xml file

- clarity_ext/service/artifact_service.py
The variable name `sample` was shadowing the parameter name `sample`.
Because of this, the loop changed the sample to some other sample and
finally returned the parent input artifact for that sample.
We saw this because the final sample was phix, but this could have
broken randomly for other samples too.
> Fix bug caused by shadowed name

- clarity_ext/resources/templates/_base/pycharm_config.xml.j2
The pycharm template now assumes that clarity-ext is contained within
the script project as a submodule, since that's how it's used here.
> 1438 - Update pycharm template

- clarity_ext/service/dilution/service.py
Control samples should be sorted as ordinary samples (robot software freak out otherwise)
> Fix transfer sort order

- clarity_ext/service/dilution/service.py
Refers to PR in clarity-snpseq #205
Prepare a list variable for printout to be used in metadatafile. This
list contains of tuples of (source, target), and is padded with empty
strings for the shorter list of the two.
> Print out unique entries of DNA and END plates in metadatafile

- clarity_ext/context.py
- clarity_ext/extensions.py
- clarity_ext/service/__init__.py
- clarity_ext/service/file_service.py
- test/unit/clarity_ext/helpers.py
- test/unit/clarity_ext/service/test_file_service.py
NOTE: This is a breaking change, in that it changes how we handle commits. Calls to commit are not required anymore. The extensions will automatically commit at the end. This has been the plan from the beginning.
Files can now be uploaded directly from the dev's workstation.
The files are not committed if the disable_commits flag is set
> Update the FileService for increased upload support

- clarity_ext/service/file_service.py
The files created by the context are kept in one directory. It needs to
be cleaned entirely between runs, but rmdir only removes an empty directory.
> Use rmtree when cleaning context files

- clarity_ext/service/step_logger_service.py
The step log may have been uploaded already and the file closed when
writing to it. For now we solve that by ignoring thrown ValueErrors.
> Add exception handling when writing to the step log

- clarity_ext/service/file_service.py
This cache will remember the mapping of artifact and file name, and be
used for print out driver files in metadata file with the name they
are uploaded with to the lims.
> Add upload cache to file_service

- clarity_ext/service/file_service.py
This check was fixed in a recent commit but it now breaks when
users have file handles with parantheses in them. The check
isn't really necessary so it's being removed.
> Remove check for file paths

- clarity_ext/data_cli.py
- clarity_ext/reporting/reporting_service.py
One can now create a project report by issuing `clarity-data project-report`.
It lists all projects and all associated UDFs in csv format.
> Add a report for projects

- clarity_ext/service/artifact_service.py
- test/integration/service/test_artifact_service.py
Each sample can map to more than one parent input artifact if it has been requeued.
> Allow more than one parent input artifact per sample

- clarity_ext/domain/container.py
- clarity_ext/service/dilution/service.py
- clarity_ext/utility/testing.py
- test/unit/clarity_ext/helpers.py
For method set_well in Container, I stumbled over a case when I don't
want to update the input artifact (which was updated), only the
internal dict self.wells. I changed the name of the method, 
set_well --> wet_well_update_artifact, 
and added a new method, set_well. set_well_update_artifact calls
set_well, and then update artifact. All references to set_well are
changed to set_well_update_artifact.
> Split up method set_well in Container

- clarity_ext/extensions.py
In ExtensionService._run() method, I call commit() after an UsageError, in order to upload the step log. 
It is required that every script evalution is validated before any files or udfs are placed in the update queue. For me, this seem reasonable, but it might still be a risk though.
> Upload step log at usage error

- clarity_ext/extensions.py
- clarity_ext/service/file_service.py
When uploading files through the file service, one can now
zip them together. In that case, only one file needs to be available
on the file handle. If zip_files is not specified, the previous logic
will work as expected, where each of the files is uploaded to a single
file handle (which must be configured specially on the step.)
Closes LIMS-1601
> Support zipping files to a file handle

- clarity_ext/service/file_service.py
- clarity_ext/utility/testing.py
Reason for this PR:
file_service -> local shared file cannot handle more than one artifacts under a file handle, that not yet have files associated with them. And this is what is needed to use more than one step logs (Step log, Warnings, Errors) which may or may not be created during a step execution. 
Here, I created a new method, local_shared_file_search_or_create(), which is used in step-logger-service only. 
I moved associated methods to a separate class, LocalSharedFileProvider, which is only to be used by file-service. I did also som internal refactoring of local_shared_file to make it more easy to read. 
Is cache used anymore? If not, should we remove the code for it?
This PR is intended for version 5.1
> 1612 refactor local shared file

- clarity_ext/domain/shared_result_file.py
- clarity_ext/service/file_service.py
- clarity_ext/service/step_logger_service.py
- clarity_ext/service/validation_service.py
- clarity_ext/utility/testing.py
Purpose:
Have separate files for warnings and errors in so that it's easier for the user to see if there are any errors/warnings. The presense of a Warnings.txt file will tell if there are warnings, which is otherwise hard to detect. 
Swap the step logger service instance in validaiton service to a aggregated step logger service. This class is wrapping a step logger service and has the same interface as the wrapped class, and have the option to add separate log services for warnings and errors. Also, add input for file name to the step logger service, to have step log names different than the file handle.
> 1567 Separate files for errors and warnings

- clarity_ext/context.py
- clarity_ext/domain/shared_result_file.py
- clarity_ext/service/step_logger_service.py
With the recently new implementation of separate files for error and
warnings, the implemention of fetch error log artifact, from context,
must be updated.
1) Add field step_logger_name to AggregatedStepLoggerService
2) Search step log artifact on basis for the file name, instead of file
handle.
> Fetch error log artifact

- clarity_ext/domain/udf.py
- clarity_ext/service/dilution/service.py
Peel away redundant information. Use udf name as shown in the lims-ui.
Error message before:
Error:  Transfer for in-FROM:A:1 (A:1@source1 => A:1@target1) - You need to provide the following measurements 'udf_current_sample_volume_ul' for '<SingleTransfer A1: [in-FROM:A:1](100,None=>[None]) =(0,0)=> A1: [out-FROM:A:1](None,None) primary / (None, None, None)>'
Error message after:
Error: You need to provide the following input 'Current sample volume (ul)', in-FROM:A:1 (A:1@source1 => A:1@target1)
> 1659 Improve error messages in dilution

- clarity_ext/domain/artifact.py
Used for showing verbose names in e.g. dilution files without
permanently updating the artifact name.
> Add field view_name into Artifact

- clarity_ext/context.py
- clarity_ext/service/file_service.py
Purpose:
User may easily by mistake upload a .xlsx file when either .csv or xml is required. Show a clear error message for this. 
In context.local_shared_file(), if the searched file is csv or xml,
check that the found artifact has a file with the right extension, i.e.
.csv or .xml. If not, cast exception with proper message.
> Add method to check file extension

- clarity_ext/service/clarity_service.py
The UDF couldn't be changed unless it had already been set. Switching between
source and target when synching between the domain object and the rest object fixes it.
> Fix a minor bug from the previous commit

- clarity_ext/mappers/clarity_mapper.py
Purpose:
To fix a bug when creating a robot file including pools (clustering.driverfile). Previously, if a pool of samples included one control sample, the entire pool was counted as a control. This had adverse effects when creating robot files. 
Action to fix the bug:
Extended constraint in deciding is_control, never assign pools as controls.
> Update rule for deciding is_control in analyte_create_object()

- clarity_ext/service/dilution/service.py
Like input_position_sort_key(), it should be a static method with only
one input argument.
> Fix sort strategy on output positions

- clarity_ext/service/artifact_service.py
This is part of a fix for https://snpseq.atlassian.net/browse/LIMS-1747. This function will be used in a clarity-ext-script, which I'm pushing to clarity-snpseq.
> Add function to fetch all analyte pairs for specific process

- clarity_ext/domain/container.py
- clarity_ext/service/dilution/service.py
Prepare clarity-ext to be able for dilution to tubes.
Add class TubeRackPositioner. Temporarily create  tube racks and place artifacts in it, in the order of the  transfers list. Therefore, sort transfers prior to placing tubes to tube racks. Also, update container with type TUBE. 
Refactorings:
method container_sort_key is moved from clarity-snpseq to here.
>  1893 dilute to tubes

- clarity_ext/service/dilution/service.py
Fix bug with symptoms:
User make a dilution with a lot of samples, that requires more than one intermediate plate.
Update method get_temporary_container(), so that it provides a new temp plate for each target plate containing looped samples. Previously there was only one temp plate. 
Refactorings:
DilutionSession.get_temporary_container() is moved to separate class (maintaining a state). get_temporarily_container() also have two new input arguments, start_id and container_template. Container template is used when diluting to tube racks, in which case the intermediate plate should still be a 96 well plate (not dimensions of the tube rack).
> Ext 1892 loop bug

- clarity_ext/service/dilution/service.py
- clarity_ext/utility/testing.py
Purpose:
Adapt TubeRackPositioner for pools, so that each pool retreive exactly one position in tube rack. 
TubeRackPositioner, which give output artifacts a position in a tube rack, get one call for each transfer. In case of pooling, there are multiple calls for the same pool. Prevent that the same pool are placed at multiple places in tube rack, by searching for artifacts that are previously added.
Add output_position_pre_batching to SortStrategy. In DilutionSession, sort transfers if a sort strategy is set, before they are treated by handlers. 
Refactorings:
* Change variable name, SharedRobotSettings.max_pipette_vol_for_row_split --> max_destination_volume.
* Change variable name, RobotSettings.sort_strategy --> robotfile_sort_strategy
> 1894 pooling to tubes

- clarity_ext/domain/container.py
- clarity_ext/service/dilution/service.py
Purpose:
1) Add tuberack as a new container type. This is used in clarity-snpseq to check if tuberack should be shown in metadatafile.
2) Configurable name prefix for tuberacks, either destination tuberack, or source tuberack.
> Ext 1925 pool with input tubes

- clarity_ext/domain/container.py
In the case of tubes, the variable `repr` is null.
> Bug fix for tubes

- clarity_ext/domain/aliquot.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/result_file.py
- clarity_ext/domain/shared_result_file.py
- clarity_ext/repository/step_repository.py
- clarity_ext/utility/testing_parse_scripts/builders.py
- clarity_ext/utility/testing_parse_scripts/fake_artifact_factory.py
- test/unit/clarity_ext/domain/test_artifact.py
- test/unit/clarity_ext/service/test_file_service.py
Purpose:
Create a slim test framework for parsing scripts.
* Instantiate ExtensionContext without connecting to network, only using fake entities
* Configure ExtensionContext with a number of fake artifact pairs (input & output)
* Configure each fake artifact pair with a number of udfs required by the script
> Ext 1970 remove duplication

- clarity_ext/context.py
Purpose:
Fix a bug. Sometimes the proper error message in UI (in the top red area) is replaced by a steplog entry. Prevent this by printing steplog entries to stout in test mode only.
> 1972, Write logs to stout in test mode only

- clarity_ext/extensions.py
- clarity_ext/repository/step_repository.py
Purpose:
Fix bug in a template script, where the input.output navigation variable refers to a shared result file instead of a sample (resultfile/analyte). 
In TemplateExtension base script, build a dictionary for input-> output variables, referring only to samples (shared result files excluded). Use this dictionary instead of the original navigation variable input.output.
> 1999, fix navigation reference bug in template extension

- clarity_ext/context.py
- clarity_ext/service/validation_service.py
- clarity_ext/utility/testing_parse_scripts/builders.py
Purpose:
By using the context validation service, logging can be directed to separate warning and error files. The idea is that the user may see from the mere existence of a warning file if there is warnings. The existence of a warning file is here kind of a proxy for a popup. The "directed" logging has been implemented in the framework for quite some time but has not yet been adapted very much in scripts. In this PR, this "directed" logging is made more available to use in scripts. 
In addition, enhance the test framework for parsing scripts to make it possible to include logging in testing.
> Add convenience methods for logging

- clarity_ext/service/dilution/service.py
Purpose:
In library dilutions, there is a need to ensure the target volume is at least minimum pipette volume PLUS pipetting robot waste volume of 1 ul. This is because right after the library dilution there is another dilution (pooling). The volumes will be too small unless waste volume is accounted for in the next step as well.
Here, there is a flag for this in the dilution_settings class.
> lims-0, Add settings for volume adjustment

- clarity_ext/service/dilution/service.py
Purpose:
The use-case that motivates this new feature is this:
I want to log min and max volumes for for each plate in a dilutions. However, when I do this logging on each batch individually, I get confusing results. Evaporation batches operates on the very same plate as the final batch and looped batches. This causes several log entries for the same plate, each log entry containing just a subset of the samples included in the step.
Here I have added a hook on batch handlers to be executed after all individual batches have been run.
> lims-0, Handle accumulated results on batches

- clarity_ext/service/dilution/service.py
The setting for dead volume is replaced to a separate handler (in
snpseq plugin). The new handler needs a reference to the main transfer (the last transfer acting on end plate)
> lims-0, Remove settings for dead volume

- clarity_ext/service/clarity_service.py
The udf update for containers was incorrectly dependant on the name
change condition.
> Fix indentation error for container updating

- clarity_ext/domain/aliquot.py
- clarity_ext/domain/analyte.py
- clarity_ext/domain/artifact.py
- clarity_ext/domain/result_file.py
- clarity_ext/mappers/clarity_mapper.py
- clarity_ext/repository/step_repository.py
Don't load all samples when creating the domain object version of an
Artifact. This was the reason for extremely long running scripts
including pools, as we are not batch fetching the samples.
A further improvement would batch fetch also (see the samples property
on the Aliquot).
> Lazy load samples on an artifact
